"""
GUI constants and text definitions
"""
import sys

def get_font_settings():
    """システムに応じて適切なフォントを取得"""
    if sys.platform.startswith('win'):
        font_family = "MS Gothic"
    elif sys.platform.startswith('darwin'):
        font_family = "Hiragino Sans GB"
    else:
        font_family = "TkDefaultFont"
    
    default_font = (font_family, 10)
    title_font = (font_family, 24, "bold")
    
    return default_font, title_font

def get_ui_text():
    """UIテキストの辞書を取得"""
    return {
        "title": "Baseball Simulation",
        "new_game": "Start New Game",
        "exit": "Exit",
        "revalidate_lineups": "Re-validate Lineups",
        "scoreboard": "Scoreboard",
        "team": "Team",
        "score": "Score",
        "hits": "Hits",
        "errors": "Errors",
        "away": "Away",
        "home": "Home",
        "inning_top": "Inning {0} Top",
        "inning_bottom": "Inning {0} Bottom",
        "outs": "Outs: {0}",
        "game_situation": "Game Situation",
        "pitcher": "Pitcher: {0}",
        "batter": "Batter: {0}",
        "strategy": "Strategy",
        "offense_strategy": "Offense Strategy",
        "defense_strategy": "Defense Strategy",
        "next_play": "Next Play",
        "play_result": "Play Result",
        "current_batter": "★Current Batter",
        "batting_order": "Batting Order",
        "bench": "Bench",
        "pinch_hit": "Pinch Hit",
        "close": "Close",
        "pitchers": "Pitchers",
        "current_pitcher": "Current Pitcher: {0}",
        "change": "Change",
        "fielders": "Fielders",
        "defense_sub": "Defensive Sub",
        "select_player": "Select player to replace:",
        "cancel": "Cancel",
        "error": "Error",
        "pinch_hit_error": "Could not make pinch hit substitution",
        "pitcher_change_error": "Could not change pitcher",
        "defense_sub_error": "Could not make defensive substitution",
        "game_start": "===== GAME START =====\n{0} vs {1}",
        "game_over": "===== GAME OVER =====",
        "final_score": "Final Score: {0} {1} - {2} {3}",
        "victory": "{0} wins",
        "tie": "It's a tie",
        "strike": "Strike out",
        "ball": "Walk",
        "stats": "Player Stats",
        "batting_stats": "Batting Stats",
        "pitching_stats": "Pitching Stats",
        "player": "Player",
        "ab": "AB",
        "h": "H",
        "avg": "AVG",
        "hr": "HR",
        "rbi": "RBI",
        "runs": "R",
        "bb": "BB",
        "k": "K",
        "single": "1B",
        "double": "2B",
        "triple": "3B",
        "ip": "IP",
        "er": "ER",
        "era": "ERA",
        "whip": "WHIP",
        "show_away": "Show Away Team",
        "show_home": "Show Home Team",
        "team_status": "Team Status",
        "team_status_unknown": "No roster loaded",
        "team_status_ready": "✓ Ready",
        "team_status_issues": "⚠ Check lineup ({0})",
        "view_lineup": "Preview",
        "manage_team": "Manage Setup",
        "title_hint": "Preview each roster before starting. You can also rerun the lineup validation from here.",
        "title_hint_ready": "Lineups look good. Press Start New Game to begin.",
        "title_hint_with_errors": "Lineup issues detected ({0}). You can resolve them from strategy menus after starting.",
        "toolbar_new_game": "Restart Game",
        "toolbar_return_title": "Return to Title",
        "toolbar_clear_log": "Clear Log",
        "toolbar_copy_log": "Copy Log",
        "toolbar_autoscroll": "Auto scroll",
        "status_default_hint": "Space: Normal batting  /  B: Bunt",
        "status_waiting": "Start a new game to enable controls",
        "status_game_over": "Game over",
        "status_restart_hint": "Use Restart Game or Return to Title to play again.",
        "normal_batting": "Normal Batting",
        "bunt_action": "Bunt",
        "log_cleared": "--- Log cleared ---\n",
        "team_preview_title_home": "Home Team Preview",
        "team_preview_title_away": "Away Team Preview",
        "team_preview_lineup": "Starting Lineup",
        "team_preview_bench": "Bench",
        "team_preview_pitchers": "Pitchers",
        "preview_order": "#",
        "preview_position": "Pos",
        "preview_name": "Player",
        "preview_eligible": "Eligible",
        "preview_role": "Role",
        "preview_status": "Status",
        "preview_no_players": "No players available",
        "preview_role_current_pitcher": "Current pitcher",
        "preview_role_available": "Available",
        "team_manage_title_home": "Manage Home Team",
        "team_manage_title_away": "Manage Away Team",
        "team_manage_lineup": "Current Lineup",
        "team_manage_bench": "Bench",
        "team_manage_pitcher": "Starting Pitcher",
        "team_manage_lineup_setup": "Lineup Setup",
        "team_manage_defense": "Edit Positions",
        "team_manage_order": "Swap Batting Order",
        "team_manage_pitcher_button": "Set Starting Pitcher",
        "team_manage_close": "Close",
        "order_swap_title": "Swap Batting Order - {0}",
        "order_swap_instruction": "Select exactly two players to swap.",
        "order_swap_success": "Swapped {0} and {1} in the batting order.",
        "order_swap_error_selection": "Please select exactly two players.",
        "pitcher_select_title": "Select Starting Pitcher - {0}",
        "pitcher_select_instruction": "Choose a pitcher to start the game.",
        "pitcher_set_success": "{0} will start the game.",
        "pitcher_set_same": "{0} is already the starting pitcher.",
    }
